language: go
sudo: required

go:
  - "1.8"

before_install:
  - echo "before_install"
install:
  - echo "install"

before_script:
  - echo "before_script"
script:
  - echo "script"

jobs:
  include:
    - stage: Custom Testing
      name: Unit-Testing
      script: echo "unit script"
    - name: Integration-Testing
      before_install: echo "Integration-Testing_before_install"
    - stage: Docker
      name: Docker-Build
      script: echo "docker build"
    - stage: Deploy
      name: deploy appliaction
      script: echo "release"
