language: go
sudo: required

before_install:
  - echo "before_install"
install:
  - echo "install"

before_script:
  - echo "before_script"
script:
  - echo "script"

jobs:
  include:
    - stage: Custom Testing
      name: Unit-Testing
      script: echo "unit script"
    - name: Integration-Testing
      before_install: echo "Integration-Testing_before_install"
    - stage: Deploy
      script: echo "release"
    - stage: Build Docker Image
      script: echo "release"
